# Generated by Django 5.2.10 on 2026-01-24 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('paper', 'Paper'), ('ewaste', 'E-Waste'), ('glass', 'Glass')], max_length=50)),
                ('weight_kg', models.FloatField()),
                ('price_per_kg', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
