# Generated by Django 5.2.10 on 2026-01-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_alter_scrap_seller_alter_scraprequest_requested_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapCategory',
        ),
    ]
