# Generated by Django 5.2.10 on 2026-01-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0008_artworkorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkorder',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
