# Generated by Django 5.2.10 on 2026-02-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0009_artworkorder_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scrap_images/'),
        ),
    ]
