# Generated by Django 5.2.10 on 2026-02-10 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('orders', '0002_alter_order_artwork'),
        ('scrap', '0010_scrap_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkorder',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='artist.artwork'),
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
    ]
