# Generated by Django 5.2.10 on 2026-02-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0011_alter_artworkorder_artwork_delete_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkorder',
            name='artist_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='commission_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
