# Generated by Django 5.2.10 on 2026-02-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0013_scraprequest_is_paid_scrappayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrappayment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
