# Generated by Django 5.2.10 on 2026-02-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0014_scrappayment_razorpay_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
