# Generated by Django 5.2.10 on 2026-02-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0017_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='available_weight',
            field=models.FloatField(default=0),
        ),
    ]
