# Generated by Django 5.2.10 on 2026-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0018_scrap_available_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraprequest',
            name='requested_weight',
            field=models.FloatField(default=0),
        ),
    ]
