# Generated by Django 5.2.10 on 2026-02-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0019_scraprequest_requested_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtworkReview',
        ),
    ]
