# Generated by Django 5.2.10 on 2026-03-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0022_scrapalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtworkOrder',
        ),
    ]
