# Generated by Django 5.2.10 on 2026-03-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0026_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='payout_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
