# Generated by Django 5.2.10 on 2026-03-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0028_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraprequest',
            name='pickup_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraprequest',
            name='pickup_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('picked', 'Picked Up'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
