# Generated by Django 5.2.10 on 2026-03-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0029_scraprequest_pickup_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraprequest',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraprequest',
            name='pickup_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='scraprequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
