# Generated by Django 5.2.10 on 2026-03-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0030_scraprequest_pickup_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraprequest',
            name='pickup_address',
        ),
        migrations.AddField(
            model_name='scraprequest',
            name='pickup_time',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20, null=True),
        ),
    ]
