# Generated by Django 5.2.10 on 2026-02-25 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_artwork_artist_alter_artwork_image_and_more'),
        ('scrap', '0022_scrapalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='scrap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrap.scrap'),
        ),
    ]
