# Generated by Django 5.2.10 on 2026-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artwork_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
