# Generated by Django 5.2.10 on 2026-03-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_artwork_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
