# Generated by Django 5.2.10 on 2026-04-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_artwork_latitude_artwork_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='longitude',
        ),
    ]
