# Generated by Django 5.2.10 on 2026-02-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('dealer', 'Dealer'), ('artist', 'Artist')], default='user', max_length=20),
        ),
    ]
