# Generated by Django 5.2.10 on 2026-03-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_artworkorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
